# Use this playbook when building locally.

site:
  title: Identity Assertion
  start_page: identity::index.adoc
content:
  sources: 
  - url: .
    tags: v1.0
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://creator-assertions.github.io/antora-ui/ui-bundle-local.zip
    snapshot: true
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_initialize_options:
        theme_variables:
          font_family: Roboto,sans-serif
